### ISSUE TITLE
benchmarks are hard to run on Ubuntu

### ISSUE THREAD

**Issue by benibela** [Yord/json-stream#5]
**Describe the bug**
Benchmarks do not run

**To Reproduce**
1. Issued pxi command.

$ make 

2. Error thrown or unexpected behavior.

  ```
  for ((i=1546300800;i<=1577836799;i++)); do printf '{"time":%d}\n' $i >> data/2019-small.jsonl; done
    /bin/sh: 1: Syntax error: Bad for loop variable

```
here /bin/sh is dash not bash

    /usr/bin/time -lp pxi 'json => json.time' < data/2019-small.jsonl > /tmp/pxi.jsonl
    /usr/bin/time: invalid option -- 'l'

```
pxi < /tmp/mlr.jsonl | diff --brief --report-identical-files - /tmp/pxi.jsonl
Files - and /tmp/pxi.jsonl differ
make: *** [Makefile:132: json-3-mlr] Error 1

```

**Expected behavior**

Benchmarks

**Desktop (please complete the following information):**
 - OS: KUbuntu 19.04
 - Version (pxi --version): github

**Comment by Yord** [comment]
Hi benibela,

thanks for the bug report! I must admit, the benchmarks are only really tested on MacOS at this point. This is definitely something I am planning to change, and soon. Your report shows, this should be further up on my list of priorities.

I am getting back to this issue soon.

Cheers
Yord
