### ISSUE TITLE
[FEATURE] Please make distinction between jsonl and json and make pxi work with both.

### ISSUE THREAD

**Issue by musicm122** [Yord/json-stream#8]
**Is your feature request related to a problem? Please describe.**

Looking at this arg I'd expect this to output json but, it outputs jsonl.
```bash
pxi --to json --chunker "jsonObj" "json => (json.field1== 'Papa')" --applier filter < "\BigFile.json" > filteredBigFile.json
```
I want the result to also be regular json. Reason being, I need to convert this to mpack. 

**Describe the solution you'd like**
I'd like to have the option to create output for regular (non-jsonl formatted) json output.
I want the result to also be regular json. Reason being, I need to convert this to mpack. 

**Describe alternatives you've considered**
I'm trying to script around the issue now but, it is requiring I roll my own additional parsing logic to convert  jsonl to json and for me this takes away some of the benefit of using this awesome tool. 

**Additional context**
NA

**Comment by Yord** [comment]
Hi [musicm122](https://github.com/musicm122), I am not actively working on `pxi` anymore. However, I may be able to help you, if you can give me more information on what you are trying to achieve. What exactly are the contents of "BigFile.json", how is it formatted? How would you expect "filteredBigFile.json" to be formatted?

Without the additional context, I am unfortunately not able to help you.

**Comment by Yord** [comment]
I am closing this issue for now. Please provide more context and I may reopen.
